import walmart from "../assests/icon/brands/walmart 1.svg";
import starbucks from "../assests/icon/brands/starbucks.svg"
import costco from "../assests/icon/brands/costco 1.svg"
import adt from "../assests/icon/brands/adt 1.svg"
import crosscom from "../assests/icon/brands/crosscom-national 1.svg"
import att from "../assests/icon/brands/att 1.svg"
import centuryLink from "../assests/icon/brands/centurylink.svg"
import Tmobile from "../assests/icon/brands/t-mobile.svg"
import Pizzahut from "../assests/icon/brands/pizzahut.svg"
import Spectrum from "../assests/icon/brands/spectrum.svg"
import WaveBroadband from "../assests/icon/brands/wavebroadband.svg"
import SpaghettiFactory from "../assests/icon/brands/spaghetti-factory.svg"
import Avon from "../assests/icon/brands/avon.svg"
import JaredsJewelry from "../assests/icon/brands/jared's-jewelry.svg"
import KayJewelers from "../assests/icon/brands/kay-jewelers.svg"
import AshleyFurniture from "../assests/icon/brands/ashley-furniture.svg"
import FamousFootwear from "../assests/icon/brands/famous_footerwear.svg"
import HobbyLobby from "../assests/icon/brands/hobby_lobby.png"
import PandaExpress from "../assests/icon/brands/panda_express.svg"
import usArmy from "../assests/icon/brands/us-army.svg"
import usAirforce from "../assests/icon/brands/us-airforce.svg"
import StanleySecurity from "../assests/icon/brands/stanleysecurity.svg"
import InterfaceSecuritySystems from "../assests/icon/brands/interface.svg"
import Lumio from "../assests/icon/brands/lumio.png"
import LeafHome from "../assests/icon/brands/leaf-home.svg"
import SeaTacInternationalAirport from "../assests/icon/brands/seatoc-airport.svg"
import DTT from "../assests/icon/brands/ddt.svg"
import LaQuinta from "../assests/icon/brands/La Quinta Inn and Suites.svg"
import RedRoofInn from "../assests/icon/brands/RedRoof_SVG_H.svg"
import Motel from "../assests/icon/brands/Motel 6.svg"
import superMotel from "../assests/icon/brands/Super 8 Motel.svg"
import Albertsons from "../assests/icon/brands/albertsons.svg"
import Kohls from "../assests/icon/brands/khols.svg"
import OliveGarden from "../assests/icon/brands/olive-garden.svg"
import RiteAid from "../assests/icon/brands/rite-adt.svg"
import DirectTV from "../assests/icon/brands/directv.svg"
// import TacoBell from "../assests/icon/brands/tacobell.svg"
import BestBuy from "../assests/icon/brands/bestbuy.svg"
import AmericanEagleOutfitters from "../assests/icon/brands/American Eagle Outfitters.svg"
import Forever from "../assests/icon/brands/forecer21.svg"
import Tesoro from "../assests/icon/brands/tesoro.svg"
import Sears from "../assests/icon/brands/sears.svg"
import Discount from "../assests/icon/brands/discount-tire.svg"
import Les from "../assests/icon/brands/lesschwab.svg"
import Campbell from "../assests/icon/brands/campbells.svg"
import Sephora from "../assests/icon/brands/sephora.svg"
import GameStop from "../assests/icon/brands/gamestop.svg"

export const brands = [walmart, starbucks, crosscom, adt, Albertsons, att, RedRoofInn, centuryLink,DirectTV, Tmobile, costco, usAirforce, Spectrum, PandaExpress, Campbell, Forever, Motel,
    FamousFootwear, LaQuinta, Discount, LeafHome, AshleyFurniture, AmericanEagleOutfitters,WaveBroadband, GameStop, OliveGarden, Pizzahut, Les, SeaTacInternationalAirport, 
    superMotel, Tesoro, usArmy,Sephora, RiteAid, InterfaceSecuritySystems, Sears, Kohls, StanleySecurity, KayJewelers, Avon, BestBuy, JaredsJewelry, Lumio, DTT];